### ISSUE TITLE
Dynamically Change displayed report

### ISSUE THREAD

**Issue by CanuckScott** [ilich/MvcReportViewer#100]
I've integrated your very useful project to my application which allows a user to select a report to view and specify parameters to pass to it.  I've broken the report MvcReportViewer viewer into a partial view and provide the report path and parameters via parameters as shown below.

This works great on load but when the user selects a new report and/or changes the parameters I need the report to be refreshed.  I have the ajax and associated controller working but for the life of me cannot get the report to change.  Can you please advise?

Thanks you,

Scott

@model MVCReportInfo
@using DW.App.Models
@using MvcReportViewer

<div class="reportviewer">
    @Html.MvcReportViewer(
                    @Model.ReportName,
                    @Model.Settings,
                    new { Height = 1000, Width = 1900, style = "border: none" }).ControlSettings(
                    new ControlSettings() { ShowParameterPrompts = false, ShowToolBar = false })
</div>

**Comment by ilich** [comment]
The control wasn't designed for AJAX, because it is just a wrapper around ASP.NET Web Forms control. I'd recommend you yo try this. Let's call **/main** the page where you show reports and user changes report parameters, and **/report** the page which has nothing except Html.MvcReportViewer call.

1. Add <div id="report"></div> to /main
2. Use $("#report").load("/report") to load new report in the browser

You can find more information on http://api.jquery.com/load/ page.

If $.load will not help then try to refresh MvcReportViewer's iframe, e.g. http://stackoverflow.com/questions/2064850/how-to-refresh-an-iframe-using-javascript

I have never tried to use MvcReportViewer in this way, but I hope it will work.

**Comment by CanuckScott** [comment]
Hello ilich and as always thanks for your time supporting this useful tool.

I'm finally getting back to this starting with your first suggestion but am wondering if something is missing from 1. in your reply  You say "Add to /main"  Was there supposed to be something after "Add"

Kind regards,

Scott

**Comment by ilich** [comment]
Sorry, it seems that GitHub did not parse my HTML. The message was "Add &lt;div id="report" /&gt; to /main".
