### ISSUE TITLE
Error After deploy

### ISSUE THREAD

**Issue by morales-franco** [ilich/MvcReportViewer#112]
Hi! I have a  Local report 
App_data --> Reports --> EmptyReport.rdlc (embedded resource)
This report only has a text.

Code View:
@Html.MvcReportViewerFluent("App_Data/Reports/NoDataReport.rdlc").ProcessingMode(ProcessingMode.Local).Attributes(new { Height = 900, Width = "100%", style = "border: none; background-color:white;" })

LocalHost is working but when I deployed, the view show a IFRAME EMPTY.

WebConfig
< add key="MvcReportViewer.AspxViewer" value="~/MvcReportViewer.aspx" />
    < add key="MvcReportViewer.AspxViewerJavaScript" value="~/Scripts/MvcReportViewer.js" />
    < add key="MvcReportViewer.ErrorPage" value="~/MvcReportViewerErrorPage.html" />
    < add key="MvcReportViewer.ShowErrorPage" value="false" />
    < add key="MvcReportViewer.ReportServerUrl" value="" /> 
    < add key="MvcReportViewer.Username" value="" />
    < add key="MvcReportViewer.Password" value="" />
    < add key="MvcReportViewer.EncryptParameters" value="False" />
    < add key="MvcReportViewer.IsAzureSSRS" value="False" />
    < add key="MvcReportViewer.LocalDataSourceProvider" value="MvcReportViewer.SessionLocalDataSourceProvider, MvcReportViewer" />
    <add key="SqlLocalDataSourceProvider.ConnectionString" value="Inventar_DESConnectionString" />

Help me please!

**Comment by eflorespalma** [comment]
Did you install in your web server this http://www.microsoft.com/en-us/download/details.aspx?id=35747 ?

**Comment by ilich** [comment]
Please try to make simple web forms application running your local report and see if it works or not. Regarding your case:

1. Enable ASP.NET errors in Web.config. < add key="MvcReportViewer.ShowErrorPage" value="True" />
2. Verify application pool permissions on the server. May be the account cannot read the report file.
3. Check you Report Viewer control version installed on the server. Please review the last comment at https://github.com/ilich/MvcReportViewer/issues/63

Let me know if there is something to be fixed in the HTML Wrapper.

**Comment by morales-franco** [comment]
Perfect is works!! Thanks very much!
