### ISSUE TITLE
[Breaking Change] Generic LocalDataSource no longer supported

### ISSUE THREAD

**Issue by daveshapiro** [ilich/MvcReportViewer#115]
I recently updated to the latest version of MvcReportViewer and a configuration that was previously working no longer works:

    @(Html.MvcReportViewerFluent(reportPath)
            .ProcessingMode(ProcessingMode.Local)
            .ReportParameters(reportParameters)
            .LocalDataSource("MySourceName", Model.Data))

The issue is in SessionLocalDataSourceProvider.Add<T>(...) which now throws a NotSupportedException.  Why such a breaking change?

**Comment by ilich** [comment]
Please check you Local Data Source provider in the web.config: &lt;add key="MvcReportViewer.LocalDataSourceProvider" value="MvcReportViewer.SessionLocalDataSourceProvider, MvcReportViewer" /&gt;

MvcReportViewer supports two data providers: SessionLocalDataSourceProvider and SqlLocalDataSourceProvider. Make sure you use SessionLocalDataSourceProvider because it saves your data table and you code works as it had been in the previous version.

SqlLocalDataSourceProvider does not allow you to store data sets. It works with SQL queries.

**Comment by ilich** [comment]
Do you think it would be nice to have to a data provider which supports SQL and data tables?

**Comment by daveshapiro** [comment]
It's already using the SessionLocalDataSourceProvider.  I haven't tracked the changes to determine what changed, but it looks like the following code is being called:

```C#
// MvcReportViewerIframe.cs
public IMvcReportViewerOptions LocalDataSource<T>(string dataSourceName, T dataSource)
{
            var provider = LocalReportDataSourceProviderFactory.Current.Create();
            provider.Add(ControlId, dataSourceName, dataSource);

            return this;
}
```

And `provider.Add(ControlId, dataSourceName, dataSource)` calls:

```C#
// SessionLocalDataSourceProvider.cs
public void Add<T>(Guid reportControlId, string dataSourceName, T dataSource)
{
            throw new NotSupportedException();
}
```

I'm currently not concerned with a SQL data provider or data tables.  I have business logic that's querying data, aggregating and enriching, and finally passing the completed `List<ReportLineItemModel>` to LocalDataSource.

**Comment by ilich** [comment]
Thank you for the report. I will try to fix it ASAP.

**Comment by ilich** [comment]
Please try MvcReportViewer 0.7.2. I have just published it to NuGet.

**Comment by daveshapiro** [comment]
That fixed it.  Thank you!
