### ISSUE TITLE
Report Data does not display

### ISSUE THREAD

**Issue by attainit** [ilich/MvcReportViewer#119]
Hi I got the report to show but it is not displaying data.  When I click on pagination and I can see that it has data but it does not display in table,  Also I can download to pdf and see data.  What is missing to make it work.

**Comment by attainit** [comment]
![capture](https://cloud.githubusercontent.com/assets/13722694/9724327/83b416e0-55a3-11e5-8a59-416ed098bb3c.GIF)

**Comment by ilich** [comment]
1. Clear cache and cookies in you browser and try again.
2. Try different browsers. Clean cache and cookies before usage. I'd recommend to use Internet Explorer since ASP.NET ReportViewer Web Control is optimized for IE.
3. Make sure you setup height and width for you report. Take a look to https://github.com/ilich/MvcReportViewer/blob/master/MvcReportViewerExample/Views/Home/Index.cshtml example.

Please let me know if this is a bug in the wrapper itself. Unfortunately I am now able to created the issue at the moment.

**Comment by bricox** [comment]
I'm seeing this same issue in chrome and IE.  I cleared by cache.  Any idea what may fix it?
