### ISSUE TITLE
Report Parameters not rendering on page

### ISSUE THREAD

**Issue by ericyeoman** [ilich/MvcReportViewer#137]
Hello,

I've tried deploying the report, but when I try to view the report I just get a blank page displayed instead of the two parameters and 'View Report' button.

I've looked through the rendered HTML and noticed there's a lot of stuff missing in the ParametersRowReportViewer element compared to my development machine. 

<tr id="ParametersRowReportViewer">
        <td colspan="3">*** This is blank, lots of stuff missing ***</td>
</tr>

I've set the ShowErrorPage to true, but no errors appear.

Couple of things:
1. The report works fine going through the report manager.
2. This is over a remote connection. Not sure if this is a problem, but it must be able to work over a remote connection.
3. All files and dll's are present.

Any help very much appreciated!

**Comment by ilich** [comment]
Hello,

First of all, set *MvcReportViewer.ShowErrorPage* to be false. It will show you an ASP.NET exception if there is any.

For SSRS reports:

1. Check firewall rules on your web-server and SSRS server.
2. Check that you've specified user account in your web.config/razor file (*MvcReportViewer.Username, MvcReportViewer.Password*).
3. Check *MvcReportViewer.ReportServerUrl* that you can access it from your web-server.

For Local Reports:

1. Check that your ASP.NET user has access to the report files on the server.

If none of those recommendations works then create simple ASP.NET Web Forms page which renders your report and run it on the server. It will be easier to debug it since Report Viewer is an ASP.NET Web Control.

Please let me know if you will find an issue in MvcReportViewer code.

**Comment by ilich** [comment]
Please also check you browser's console to see if there are JavaScript error on the page, e.g. 
jQuery is not loaded or you have a ScriptManager error.

**Comment by ericyeoman** [comment]
Hello ilich,

I have just discovered it is a problem with the Report Server configuration, so no problems with MvcReportViewer.

Apologies for not responding sooner, only worked this out in the last hour myself. Thanks for your help, and thanks for the software.
