### ISSUE TITLE
How to , MVC5/6 + SPA (Angular JS)

### ISSUE THREAD

**Issue by tessSnap** [ilich/MvcReportViewer#138]
How do you go about integrating this with  SPA with angular JS ? Any guidance will be helpful

**Comment by ilich** [comment]
Use MvcReportViewer in POST mode. The helper will render a form and an iframe. You can user form's input tags to setup new report parameters and then submit the code once you're ready. You cannot use MvcReportVIewer encrypted mode because you will not have access to the keys on the client side.

Please let me know if you will have any idea how to enhance the project and make it easier to use.

**Comment by adopilot** [comment]
@ilich Is there any sapmle whic showin how to POST params to reportviewer contol ?

**Comment by ilich** [comment]
Yes. Please check https://github.com/ilich/MvcReportViewer/blob/master/MvcReportViewerExample/Views/Home/Post.cshtml
