### ISSUE TITLE
Using MVCReportViewer with load balanced servers

### ISSUE THREAD

**Issue by damdave1** [ilich/MvcReportViewer#153]
My environment has 4 web servers being load balanced and those 4 web servers access a single report server.  In this scenario, if a user's request, resulting from a drill-down link, does not go to the server that originated the top level of the report, the report server does not deliver the report correctly.  Is there a way to configure the MVCReportViewer to work in this scenario?  I've cloned the source code but not having much luck figuring out if their is flexibility to make this work.  Although using sticky sessions may solve this issue I would rather not go that route.

Thanks!
David

**Comment by ilich** [comment]
Hello David,

Will ASP.NET Session Server or session state store in SQL Server help in your case? If yes then you can configure it in Web.config.

Otherwise I have never experienced drill-down reports on a web farm. Have you ever done this using Web Forms? Could you send me sample code on an article how you can do it in Web Forms world?


Sincerely,
Ilya

**Comment by ilich** [comment]
Please reopen the ticket if you will have an idea for MvcReportViewer enhancement or you will find a bug related to web-farms. 

I think it might be valuable for the community if you will provide the details how you solved your problem.

Sincerely,
Ilya
