### ISSUE TITLE
Forms Authentication

### ISSUE THREAD

**Issue by nkhamis** [ilich/MvcReportViewer#33]
I have a custom set of user credentials supplied by forms authentication.

Based on their role and access, I want access to certain reports (without having to have Windows Creds).

Does MvcReportViewer support this?

**Comment by ilich** [comment]
This feature requires calling unmanaged code (Windows API). I do not think this is a good idea to do this because we may ended up having problems with applications running in medium or lover trust levels. I think this functionality has to be implemented by a particular application itself, especially if it is going to be an internal application running in a trusted network.
