### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by livesoftware** [ilich/MvcReportViewer#58]
Hi ilich,

Finally got around to implementing this.  How can we get error messages?   I'm just getting redirected to the Service unavailable page.  Thanks.

**Comment by npavgi** [comment]
@livesoftware - MvcReportViewer does a Trace.Warn(<exception message>) so you should be able to view them if you have enabled Tracing on your application and go to http://<server>/WebSite/trace.axd. Have not tried it myself though.

@ilich - Not everyone enables tracing, and it is way simpler to see the exception message on the error redirect page. At the very least, can the MvcReportViewerErrorPage.html page can be made to accept and display the exception message?

So, instead of:
```C#
Response.Redirect(errorpage);
```
do
```C#
Response.Redirect(errorpage + "?errorMessage=exception.Message");
```
And within MvcReportViewerErrorPage.html
```JS
function getParams() {
    //get URL parameters
}
```
```HTML
document.write("Error Message:" + getParams()["errorMessage"];
```

**Comment by ilich** [comment]
I think I will make it simpler. If user does not want to use custom error page then I will show ASP.NET exception page. It provides all needed information for debugging purposes. Thank you for the recommendation.

**Comment by ilich** [comment]
You can set MvcReportViewer.ShowErrorPage to False in Web.config to show exception information on the page instead of redirect to your custom error page.

**Comment by ilich** [comment]
Added error and errorType parameters to the error page.
