### ISSUE TITLE
"The given key was not present in the dictionary" in IE 11, works in Chrome.

### ISSUE THREAD

**Issue by natewaid** [ilich/MvcReportViewer#63]
I get this error in IE 11 on reports that accept multi-value parameters.  Reports with multi-value parameters work correctly in Chrome.  Is there some config settings for IE that I am missing somewhere?

![image](https://cloud.githubusercontent.com/assets/6249408/6156407/a3be2aa4-b1ff-11e4-8e24-d5711f5b6f6c.png)

**Comment by ilich** [comment]
This is strange error. You do not need any special settings for IE 11. I think it might be related to the way IE does URL encoding or its iframe implementation. Anyway, I do not have enough information here to investigate the issue at the moment: I do not know your input parameters and I do not have your report. 

Please download the latest source code and try to debug your report using sample application. Please let me know what needs to be fixed or provide a patch. I will merge it to the main repository.

**Comment by natewaid** [comment]
I discovered the cause.  For the report view ControlSettings, I had ShowParameterPrompts = true.  I changed to false and it worked.  Not sure why this would cause that server error.  May be something worth looking into.  I downloaded all source code and looked through but could not identify this problem.  Thanks for your prompt response.

**Comment by ilich** [comment]
I have checked your case. Unfortunately I am not able to recreate the issue.

**Comment by adamknudsen** [comment]
I realize this is closed, but I recently experienced the same issue and thought I'd share the resolution we got to.
We initially had the same error (on IE and Firefox but not Chrome).  We then set ShowParameterPrompts = false.  This then revealed another problem in the report viewer: Method not found: 'Boolean Microsoft.ReportingServices.Common.DateTimeUtil.TryParseDateTime(System.String, System.IFormatProvider, System.DateTimeOffset ByRef, Boolean ByRef)'.
It turns out we had a slightly newer version of Microsoft.ReportViewer.Common.dll in the bin directory of the MVC project than was in the GAC on the server.  Apparently, the signature of this method has changed in the not too distant past.  You could probably fix this by updating the report viewer on the server, but we chose to downgrade Microsoft.ReportViewer.Common.dll in our bin directory.  After replacing the dll, we were able to reenable ShowParameterPrompts and run the reports in the other browsers.

**Comment by ilich** [comment]
Thank you for the explanation!

**Comment by coymeeks** [comment]
I ran into this same issue today but none of the suggested resolutions helped in my case so I figured I'd pass along my resolution.
My web application has ReportViewer.dll v11 (**Report viewer 2012**) in its bin folder that gets deployed out with the application.

The fix in my case was to install **Microsoft SQL Server Types CLR 2012 (x64)** and **Report Viewer 2012 Runtime** on the WEB server.  **SQL Server Types 2012** is a pre-requisite to **Report Viewer 2012 Runtime** so it must be installed first.  After installing these two components, reports began to render in IE11.

Download links:

1. Microsoft SQL Server Types CLR 2012 (x64):  http://go.microsoft.com/fwlink/?LinkID=239644&clcid=0x409
2. Report Viewer 2012 Runtime:  https://www.microsoft.com/en-us/download/details.aspx?id=35747

Hope this helps some folks!

Cheers
