### ISSUE TITLE
ASP.NET session has expired or could not be found

### ISSUE THREAD

**Issue by mkamoski** [ilich/MvcReportViewer#66]
Dear MvcReportViewer Developers -- 
Please help.
I am trying to run the example.
My report starts to load then shows the following error in the UI.
ASP.NET session has expired or could not be found
I have the app set to NOT show the error page.
I have tried adding this line...
<add key="MvcReportViewer.LocalDataSourceProvider" value="MvcReportViewer.SessionLocalDataSourceProvider, MvcReportViewer" />
...to the web config file, as specified by this github project main page but it was NOT in the downloaded source code for the example, but that did not help.
I know my report runs because I can just put in the server+report into a browser and get the report.
Can you help? What can fix this problem for me?
Please advise.
Thanks.
-- Mark Kamoski

**Comment by mkamoski** [comment]
Fixed it by setting "KeepSessionAlive" both in the declarative markup (code-infront) for the report control declarations (such as the ASPX page) which was (I think) just 2 places, and also I changed all code where KeepSessionAlive is set and I made sure it was set to True, which was 1 place in the fluent code (I think). Anyway, works like a charm. Also, I left in the web config change that I noted in my post above. I am NOT going to close this issue because the Example code download should be updated to save others the trouble of fixing as a I did. Otherwise, this project is GREAT and I really thank you for filling the huge gap that MVC has in it where there is virtually no SSRS report viewer support but for this saving excellent project. Thanks. -- Mark Kamoski

**Comment by mkamoski** [comment]
Dear Developers -- 

BTW, this is a follow-up to my comments above.

I did also find that I can also set the keepsessionalive property declaratively like this...

@section Code {
@Html.MvcReportViewer(
"/MyFolder1/MyFolder2/MyReport3",
null,
new { Height = 600, Width = 1024, style = "border: 1px solid lightgray;", keepsessionalive = "true" })
}

...and doing that (plus what I mention in my other posts above) seems to really do the trick.

HTH.

Thanks.

-- Mark Kamoski

**Comment by arageshashi** [comment]
I have made change is my code as suggested in above code snapshot but still receiving 
"ASP.NET session has expired or could not be found"  error.

**Comment by ilich** [comment]
It seems to be IIS/ASP.NET configuration issue. I have checked few blogs. These are the recommendations:

1. Add ```<sessionState timeout ="120" mode="InProc" cookieless="false" />``` to your Web.config. 

2. Set **KeepSessionAlive = false** and **KeepSessionAlive = false**. See https://github.com/ilich/MvcReportViewer/blob/master/MvcReportViewerExample/Views/Home/Fluent.cshtml as an example how to do that. You should set these properties in ControlSettings object.

3. Use Session Server or SQL Server if your website is running on as web-farm.

4. >During testing a while ago I had changed the "Maximum Worker Processes" (in the advanced settings of the application pool) to a value greater than 1 - this was causing multiple W3WP.Exe's to be launched which of course weren't sharing memory so inProc session state was failing.
> Changing the Maximum Worker Processes back to 1 cured my problem.
From http://sqlblog.com/blogs/roman_rehak/archive/2007/05/04/asp-net-session-has-expired-error-in-the-reportviewer-control.aspx

Also check http://stackoverflow.com/questions/9492677/asp-net-session-has-expired-or-could-not-be-found-because-the-session-session and http://www.c-sharpcorner.com/Blogs/8786/reportviewer-Asp-Net-session-has-expired.aspx

**Comment by NareshMittal** [comment]
Nothing worked except changing the value of 'Maximum Worker Process' to 1 in App Pool advance settings. Have struggled for a solution for quite some time and finally answer from ilich did the trick. Thank you.

**Comment by Manirajss** [comment]
For me in azure platform setting ARR Affinity ON fixed the issue.

https://stackoverflow.com/a/59842081/3186681
