### ISSUE TITLE
HTTP 500 Internal Server Error in my app

### ISSUE THREAD

**Issue by demispb** [ilich/MvcReportViewer#71]
The same error of Issue #40 , i just add to my webconfig the line

<add path="Reserved.ReportViewerWebControl.axd" verb="*" type="System.ServiceModel.Activation.HttpHandler, System.ServiceModel.Activation, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" validate="false" />

And give a 500 error on every page of my app...delete the line and my site shows Ok...what can i do, i have MVC 5, Visual Studio 2013.

**Comment by ilich** [comment]
I cannot tell you what is wrong with your particular installation. I'd guess you need to install Report Viewer Control on the server. http://www.microsoft.com/en-us/download/details.aspx?id=35747

Otherwise I'd recommend you to clone the source code, build it on your machine and debug. Please let me know if you will find a bug.

**Comment by ilich** [comment]
I cannot tell you what is wrong with your particular installation. I'd guess you need to install Report Viewer Control on the server. http://www.microsoft.com/en-us/download/details.aspx?id=35747

Otherwise I'd recommend you to clone the source code, build it on your machine and debug. Please let me know if you will find a bug.

**Comment by demispb** [comment]
The error is on my Dev machine, not on the server, debug on VS and doesn't show any error on VS, only show white page and in the browser console show the 500 error

**Comment by ilich** [comment]
It might be DLL conflict, e.g. reported Umbraco issue in #60. What I'd do in your case is to get the source code and run sample application. If it work then there is a conflict in your application. If it does not work then try to reinstall Report Viewer Control. Also try to show you report in the sample application to make sure that it is not the issue with ReportViewer wrapper itself. That's all I can recommend now with the information you provided in the ticket.

**Comment by ilich** [comment]
Another idea. If your reports worked from the sample application, I would start adding other libraries from your application one by one to see which will break the sample app.

**Comment by demispb** [comment]
@ilich Thanks for your comments, finally i get my site running, first i get my site back by add on my web.config the line <validation validateIntegratedModeConfiguration="false"/>, but the reportviewwer doesn't work, later i double check all the MvcReportViewer config's and found a mistake on the report server address character, after this i get my reports running on MVC OK, later delete the line that i added at first try and my site works Ok !!, well, something weird but i got now my site back and the reports running. Thanks and sorry for my English, Greetings from Cuba.

**Comment by demispb** [comment]
the line code doesn´t show on my comment:
It was < validation validateIntegratedModeConfiguration="false" / >
