### ISSUE TITLE
When call Mvc ReportViewer from another domain, SecurityError happend 

### ISSUE THREAD

**Issue by syaung** [ilich/MvcReportViewer#75]
When I call web service Mvc ReportViewer from another domain, I got SecurityError at request to MvcReportViewer.aspx page.

Uncaught SecurityError: Blocked a frame with origin "http://localhost:2000" from accessing a frame with origin "http://localhost:52974". Protocols, domains, and ports must match.

Could you please advice How to fix it?

**Comment by ilich** [comment]
This issue is not related to the MvcReportViewer. Please check MDN document about Same-origin policy and CORS(https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy) as the starting point. You can also read http://blog.cakemail.com/the-iframe-cross-domain-policy-problem/ and http://javascript.info/tutorial/same-origin-security-policy. 

I'd recommend to host MvcReportViewer code on the same domain name and port. If you do not want to copy local reports to multiple places there is a work around using NTFS symbolic links created by mklink command (http://ss64.com/nt/mklink.html).
