### ISSUE TITLE
question about a change to MvcReportViewer.aspx to support IE11 Enterprise Mode

### ISSUE THREAD

**Issue by mkamoski** [ilich/MvcReportViewer#96]
I am having some trouble with my MVC site in IE11 with EnterpriseMode=On.
I go a suggestion to make a change for all DOCTYPE tags in the project.
So, in this page...
MvcReportViewer.aspx
...can one safely change this line...
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
...to be the following line...
<!DOCTYPE html>
...or will that cause any issues?
What do you think?
Please advise.
Thanks.
-- Mark Kamoski

**Comment by ilich** [comment]
I have updated doctype to be html. I haven't found issues so far. I don't think you will have issues with the helper itself, because it does not use any HTML 4.01 specific features. There might be potential issues with Report Viewer Web Control itself which I am not aware of.

The fix will come with the next release.
